In [ ]:
# Where to libraries live?

import random# as rdn_

In [ ]:
random.__file__

In [ ]:
rdn_.__file__

In [ ]:
# Lets take a look in any text editor (or Spyder)

In [ ]:
# def randint

random.randint(2, 10)

In [ ]:
# def randrange

In [ ]:
help(random)

When I was 4 years old, I wrote my very first program in BASIC on my Atari 800XL.  In it, the computer randomly picked a whole number between 1 and 100, and the user had 10 chances to guess the number.  Every time the user guessed a number, they would be told either that the number was “too low”, “too high” or “correct”.  If the user used up all 10 chances without guessing correctly, they were told “you lose” and the game would end.

You now have been taught enough to write this program in Python.

You should write the game above (I’d advise using Spyder) along with the following extra features that 4-year old Dan didn’t implement :

- a score, which starts at 1000 and which reduces by 100 for every unsuccessful guess, and which is displayed if the user wins
- the user’s guesses are stored in a list and printed once the game is over
- the game asks if the player wants to play again after every game ends
- after each game, the player’s score is checked against the current high-score (default is 0) and if the last score is higher than the recorded high score then this replaces the high score.

If you do all that with time to spare, add some bells and whistles of your choosing!

You have 45 minutes (+10 minute break), and you should work as a group.

In [4]:
import random

# counter_
guess_list = []
high_score = 0

current_score = 1000
computer_guess = random.randint(1, 100)
counter = 0

while True:
    
    
    user_guess = int(input("Please enter your guess (1-100 inc): "))
    while user_guess > 100 or user_guess < 0:
        user_guess = int(input("Please enter your guess (1-100 inc): "))

    counter += 1
    
    if user_guess < computer_guess:
        print("Too low")
        current_score -= 100
        guess_list.append(user_guess)
    elif user_guess > computer_guess:
        print("Too high")
        current_score -= 100
        guess_list.append(user_guess)
    else:
        print("Correct")
        print("Well done you've won")
        guess_list.append(user_guess)
        print(f"You have scored {current_score}")
        break

    if counter == 10:
        print("you've run out of guesses")
        break

if user_score > high_score:
    high_score = user_score
    print(f"Your guesses were {guess_list}")
    print(f"You've just achieved a new high score of {high_score}")
    
print(f"Your guesses were {guess_list}")


Please enter your guess (1-100 inc): 1
Too low
Please enter your guess (1-100 inc): 99
Too high
Please enter your guess (1-100 inc): 50
Too low
Please enter your guess (1-100 inc): 78
Too low
Please enter your guess (1-100 inc): 54
Too low
Please enter your guess (1-100 inc): 15
Too low
Please enter your guess (1-100 inc): 20
Too low
Please enter your guess (1-100 inc): 10
Too low
Please enter your guess (1-100 inc): 10
Too low
Please enter your guess (1-100 inc): 30
Too low
you've run out of guesses
Your guesses were [1, 99, 50, 78, 54, 15, 20, 10, 10, 30]


In [13]:
#high_score = random.randint(1,10)

print(f"You've just achieved a new high score of {high_score}")

You've just achieved a new high score of 4


In [15]:
print("You've just achieved a new high score of {high_score}")

You've just achieved a new high score of {high_score}


### 

### Numpy
#### 1D:22

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])


In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
type(a)

numpy.ndarray

In [19]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 4, 6, 8, 10]
list_3 = [3, 6, 9, 12, 15]

a = np.array([list_1, list_2, list_3])
print(a)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]


In [20]:
type(a)

numpy.ndarray

In [21]:
a[0]

array([1, 2, 3, 4, 5])

#### shape
#### 1D:30

In [22]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


In [26]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)

(2, 3)


In [27]:
# same as above - just new line...
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)

(2, 3)


In [29]:
c = np.array([[[1, 2, 3],[4, 5, 6]],
              [[10, 20, 30],[40, 50, 60]]])
print(c.shape)

(2, 2, 3)


In [30]:
# same as above - just new line...

c = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[10, 20, 30],
               [40, 50, 60]]])

print(c.shape)

(2, 2, 3)


In [31]:
#### ndim

c = np.array([[[1, 2, 3],[4, 5, 6]],
              [[10, 20, 30],[40, 50, 60]]])


print(c.ndim)

3


In [32]:
#### ndim

c2 = np.array([[[1, 2, 3, 1],[4, 5, 6, 1]],
              [[10, 20, 30, 1],[40, 50, 60, 1]]])


print(c2.ndim)

3


#### NumPy - Arrays - Homogeneity

In [ ]:
d = np.array([[1, 2, 3], [1, 2]])

#### NumPy - Arrays - Mathematical Operations

In [34]:
a = np.array([1, 2, 3, 4, 5])

a = a * 4
print(a)

[ 4  8 12 16 20]


In [36]:
list_a = [1, 2, 3, 4, 5]

list_a * 4

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

#### Slicing

In [37]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

c = b[1] * 2
print(c)

print(b[0][2])

[12 14 16 18 20]
3


#### Statistics

##### 1D:35

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print( a.mean())


b = np.array([[1, 2, 3, 4, 5], # sum of these = 15 / 5 = 3
              [6, 7, 8, 9, 10]]) #  sum of these = 40 / 5 = 8


# i.e., 1+6=7/2=3.5 2+7=9/2=4.5....
print(np.mean(b, axis = 0 ))


print(np.mean(b, axis = 1 ))



#### Dot Prodcut

##### 1D:36

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])

dp = np.dot(a, b)
print(dp)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 1, 1, 1, 1])

dp = np.dot(a, b)
print(dp)

#### vstack + hstack
##### 1D:37-38

In [ ]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

list_to_add = [3, 6, 9, 12, 15]

b = np.vstack([b, list_to_add])

print(b)

In [ ]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

col_to_add = [[6], [12]]

b = np.hstack([b, col_to_add])

print(b)

In [ ]:
#### Removing Duplicate Data
#### 1D:39

In [ ]:
b = np.array([[1, 2, 3, 4, 5], # notice 5 in each line
              [5, 6, 7, 8, 9]])

b = np.unique(b)

print(b)

In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3]])

b = np.unique(b, axis=0)

print(b)

In [ ]:
#### Exercise 4
#### 1D:41

ages = [18, 19, 22, 23, 24, 27, 29, 31, 34, 46]
prev_admissions = [0, 3, 2, 0, 0, 1, 2, 0, 0, 1]
addmited_on_time = [1, 0, 0, 0, 0, 1, 1, 1, 0, 0]

In [90]:
##### Creating a DF
###### 1D:45-47

import pandas as pd

df = pd.DataFrame()

list_of_patient_ids = [1, 2, 3]
list_of_name = ["Bob Rogers", "Fred Miles", "Janet Smith"]
list_of_ages = [46, 31, 27]
list_of_locations = ["Plymouth", "Truro", "Exeter"]

df["patient_ID"] = list_of_patient_ids
df["name"] = list_of_name
df["age"] = list_of_ages
df["location"] = list_of_locations
#df['elliotts_col'] = list_of_name

print(df)

   patient_ID         name  age  location
0           1   Bob Rogers   46  Plymouth
1           2   Fred Miles   31     Truro
2           3  Janet Smith   27    Exeter


In [91]:
#### Specifying a DataFrame Index
##### 1D:48

df.set_index('patient_ID', inplace=True)

In [92]:
df

name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter

In [93]:
#### Retrieving specific records using loc
##### 1D:49

print(df.loc[2])

name        Fred Miles
age                 31
location         Truro
Name: 2, dtype: object


In [97]:
print(df.loc[[2, 3]])

                   name  age location
patient_ID                           
2            Fred Miles   31    Truro
3           Janet Smith   27   Exeter


In [98]:
print(df.loc[1:3])

                   name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter


In [99]:
df

name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter

In [100]:
#### Retrieving specific columns
##### 1D:50

print(df['name'])

patient_ID
1     Bob Rogers
2     Fred Miles
3    Janet Smith
Name: name, dtype: object


In [101]:
print(df['location'])

patient_ID
1    Plymouth
2       Truro
3      Exeter
Name: location, dtype: object


In [105]:
print(df[['location','age']])

            location  age
patient_ID               
1           Plymouth   46
2              Truro   31
3             Exeter   27


In [106]:
#### Adding more Rows

df2 = pd.DataFrame({"patient_ID" : [4, 5],
                  "name" : ["Lucy Rivers", "Dave Jones"], # col names must match!
                  "age" : [28, 61],
                  "location" : ["Plymouth", "Plymouth"]})

df2

patient_ID         name  age  location
0           4  Lucy Rivers   28  Plymouth
1           5   Dave Jones   61  Plymouth

In [108]:
df2.set_index("patient_ID", inplace= True)

In [109]:
df2

name  age  location
patient_ID                            
4           Lucy Rivers   28  Plymouth
5            Dave Jones   61  Plymouth

In [110]:
df

name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter

In [111]:
#df2.set_index("patient_ID", inplace= True)

df = pd.concat([df, df2])

print(df)

                   name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter
4           Lucy Rivers   28  Plymouth
5            Dave Jones   61  Plymouth


In [112]:
df

name  age  location
patient_ID                            
1            Bob Rogers   46  Plymouth
2            Fred Miles   31     Truro
3           Janet Smith   27    Exeter
4           Lucy Rivers   28  Plymouth
5            Dave Jones   61  Plymouth

In [113]:
list_of_prev_admissions = [True, True, False, False, False]
df["previoulsy_admitted"] = list_of_prev_admissions
print(df)

                   name  age  location  previoulsy_admitted
patient_ID                                                 
1            Bob Rogers   46  Plymouth                 True
2            Fred Miles   31     Truro                 True
3           Janet Smith   27    Exeter                False
4           Lucy Rivers   28  Plymouth                False
5            Dave Jones   61  Plymouth                False


In [114]:
df

name  age  location  previoulsy_admitted
patient_ID                                                 
1            Bob Rogers   46  Plymouth                 True
2            Fred Miles   31     Truro                 True
3           Janet Smith   27    Exeter                False
4           Lucy Rivers   28  Plymouth                False
5            Dave Jones   61  Plymouth                False

#### Exercise 5
##### 1D: 53

) Stores the four columns as separate lists (in real applications, you can use functions to read in real data from a .csv file, in case you’re worried!)
2) Creates a new Pandas DataFrame that contains this data in named columns, with MIU Number as the index
3) Prints out the data for MIU Numbers 571 and 732
4) Prints out the location column of the data
5) Adds a new column that stores the mean number of patients seen per day, which are 4, 3, 3, 1, 2 respectively, then prints the dataframe.
6) Adds a new row representing the data for MIU number 901, which is a morning MIU with X-Ray facilities in Callington, that sees 5 patients per day, then prints the dataframe.

In [115]:
#### Exercise 5
##### 1D: 53

df = pd.DataFrame({"miu_number" : [463, 571, 614, 732, 817],
                   "location" : ["Lostwithiel", "St Austell", "Truro", "Looe", "Camborne"],
                   "xray" : [True, False, True, False, True],
                   "open" : ["Morning", "Afternoon", "Afternoon", "Morning", "Evening"],
                  })

print(df)

   miu_number     location   xray       open
0         463  Lostwithiel   True    Morning
1         571   St Austell  False  Afternoon
2         614        Truro   True  Afternoon
3         732         Looe  False    Morning
4         817     Camborne   True    Evening


In [118]:
df.set_index("miu_number", inplace=True)

In [119]:
# this will display the DF
df

location   xray       open
miu_number                               
463         Lostwithiel   True    Morning
571          St Austell  False  Afternoon
614               Truro   True  Afternoon
732                Looe  False    Morning
817            Camborne   True    Evening



5) Adds a new column that stores the mean number of patients seen per day, which are 4, 3, 3, 1, 2 respectively, then prints the dataframe.
6) Adds a new row representing the data for MIU number 901, which is a morning MIU with X-Ray facilities in Callington, that sees 5 patients per day, then prints the dataframe.

In [120]:
#3) Prints out the data for MIU Numbers 571 and 732

print(df.loc[[571, 732]])

              location   xray       open
miu_number                              
571         St Austell  False  Afternoon
732               Looe  False    Morning


In [121]:
# 4) Prints out the location column of the data

print(df['location'])

miu_number
463    Lostwithiel
571     St Austell
614          Truro
732           Looe
817       Camborne
Name: location, dtype: object


In [128]:
# 5) Adds a new column that stores the mean number of patients seen per day, which are 4, 3, 3, 1, 2 
# respectively, then prints the dataframe.

avg_pats = [4, 3, 3, 1, 2]

df['avg_pts_seen'] = avg_pats

print(df)

               location   xray       open  avg_pts_seen
miu_number                                             
463         Lostwithiel   True    Morning             4
571          St Austell  False  Afternoon             3
614               Truro   True  Afternoon             3
732                Looe  False    Morning             1
817            Camborne   True    Evening             2


In [133]:
# 6) Adds a new row representing the data for MIU number 901, which is a morning MIU 
# with X-Ray facilities in Callington, that sees 5 patients per day, then prints the dataframe.

# df_bup = df.copy()

df_new_row = pd.DataFrame({"miu_number" : [901],
                          "location" : ["Callington"],
                          "xray" : [True],
                          "open" : ["Morning"],
                          "avg_pts_seen" : [5]})

df_new_row.set_index("miu_number", inplace=True)

In [135]:
df_new_row

location  xray     open  avg_pts_seen
miu_number                                         
901         Callington  True  Morning             5

In [136]:
df = pd.concat([df, df_new_row])
print(df)

               location   xray       open  avg_pts_seen
miu_number                                             
463         Lostwithiel   True    Morning             4
571          St Austell  False  Afternoon             3
614               Truro   True  Afternoon             3
732                Looe  False    Morning             1
817            Camborne   True    Evening             2
901          Callington   True    Morning             5


In [ ]:
pd.read_xls()

In [82]:
pd.read_csv('country_details.csv')

Afghanistan  38928346   652860   60
0                Albania   2877797    27400  105
1                Algeria  43851044  2381740   18
2                Andorra     77265      470  164
3                 Angola  32866272  1246700   26
4    Antigua and Barbuda     97929      440  223
..                   ...       ...      ...  ...
189            Venezuela  28435940   882050   32
190              Vietnam  97338579   310070  314
191                Yemen  29825964   527970   56
192               Zambia  18383955   743390   25
193             Zimbabwe  14862924   386850   38

[194 rows x 4 columns]

In [81]:
col_headers = ['country','population','land_area','density']

pd.read_csv('country_details.csv', names = col_headers)

country  population  land_area  density
0    Afghanistan    38928346     652860       60
1        Albania     2877797      27400      105
2        Algeria    43851044    2381740       18
3        Andorra       77265        470      164
4         Angola    32866272    1246700       26
..           ...         ...        ...      ...
190    Venezuela    28435940     882050       32
191      Vietnam    97338579     310070      314
192        Yemen    29825964     527970       56
193       Zambia    18383955     743390       25
194     Zimbabwe    14862924     386850       38

[195 rows x 4 columns]

In [68]:
df = pd.read_csv('country_details.csv', names = col_headers)

df['calc'] = df['population'] / df['land_area']

0       59.627403
1      105.029088
2       18.411348
3      164.393617
4       26.362615
          ...    
190     32.238467
191    313.924530
192     56.491778
193     24.729893
194     38.420380
Name: calc, Length: 195, dtype: float64